/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoundaryRouteImport } from './routes/boundary'
import { Route as HandoffsRouteImport } from './routes/handoffs'
import { Route as HostPathRouteImport } from './routes/host-path'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoundaryRoute = BoundaryRouteImport.update({
  id: '/boundary',
  path: '/boundary',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffsRoute = HandoffsRouteImport.update({
  id: '/handoffs',
  path: '/handoffs',
  getParentRoute: () => rootRouteImport,
} as any)
const HostPathRoute = HostPathRouteImport.update({
  id: '/host-path',
  path: '/host-path',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boundary': typeof BoundaryRoute
  '/handoffs': typeof HandoffsRoute
  '/host-path': typeof HostPathRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boundary': typeof BoundaryRoute
  '/handoffs': typeof HandoffsRoute
  '/host-path': typeof HostPathRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boundary': typeof BoundaryRoute
  '/handoffs': typeof HandoffsRoute
  '/host-path': typeof HostPathRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/boundary' | '/handoffs' | '/host-path'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/boundary' | '/handoffs' | '/host-path'
  id: '__root__' | '/' | '/boundary' | '/handoffs' | '/host-path'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoundaryRoute: typeof BoundaryRoute
  HandoffsRoute: typeof HandoffsRoute
  HostPathRoute: typeof HostPathRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boundary': {
      id: '/boundary'
      path: '/boundary'
      fullPath: '/boundary'
      preLoaderRoute: typeof BoundaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoffs': {
      id: '/handoffs'
      path: '/handoffs'
      fullPath: '/handoffs'
      preLoaderRoute: typeof HandoffsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host-path': {
      id: '/host-path'
      path: '/host-path'
      fullPath: '/host-path'
      preLoaderRoute: typeof HostPathRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoundaryRoute: BoundaryRoute,
  HandoffsRoute: HandoffsRoute,
  HostPathRoute: HostPathRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
